export const NAME = "TestDetail";

export const GENERATE_TEST_RUNNER_DETAIL = `${NAME}/GENERATE_TEST_RUNNER_DETAIL`;
export const FETCH_ERROR_SCREENSHOT = `${NAME}/FETCH_ERROR_SCREENSHOT`;
export const GENERATE_DEVICE_INFO = `${NAME}/GENERATE_DEVICE_INFO`;
