export const NAME = "Dashboard";

export const TRANSFORM_TEST_RESULT = `${NAME}/TRANSFORM_TEST_RESULT`;
export const FETCH_TEST_RESULT = `${NAME}/FETCH_TEST_RESULT`;
export const GENERATE_CHART_DATA = `${NAME}/GENERATE_CHART_DATA`;
