export const NAME = "Dashboard";

export const TRANSFORM_TEST_RESULT = `${NAME}/TRANSFORM_TEST_RESULT`;
export const FETCH_TEST_RESULT = `${NAME}/FETCH_TEST_RESULT`;
export const GENERATE_TEST_STATUS_CHART_DATA = `${NAME}/GENERATE_TEST_STATUS_CHART_DATA`;
export const GENERATE_DEVICE_INFO_CHART_DATA = `${NAME}/GENERATE_DEVICE_INFO_CHART_DATA`;
export const FETCH_RUNNER_DETAIL = `${NAME}/FETCH_RUNNER_DETAIL`;
